"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-05 10:52:23.759333
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(length=60), nullable=True),
    sa.Column('vertical', sa.String(length=20), nullable=True),
    sa.Column('data_origin', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tool_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('surface', sa.String(length=10), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('key_kind', sa.String(length=10), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('key_prefix', sa.String(length=12), nullable=True),
    sa.Column('caller_ip', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_audit_log_at'), 'tool_audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_tool_audit_log_customer_id'), 'tool_audit_log', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tool_audit_log_outcome'), 'tool_audit_log', ['outcome'], unique=False)
    op.create_index(op.f('ix_tool_audit_log_tool'), 'tool_audit_log', ['tool'], unique=False)
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('account_status', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('vertical', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('profile_metadata', sa.JSON(), nullable=True),
    sa.Column('uuid', sa.String(length=60), nullable=True),
    sa.Column('customer_uuid', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('arc_type', sa.String(length=50), nullable=True),
    sa.Column('arc_phase', sa.String(length=20), nullable=True),
    sa.Column('arc_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_account_customer_industry', 'accounts', ['customer_id', 'industry'], unique=False)
    op.create_index('idx_account_customer_region', 'accounts', ['customer_id', 'region'], unique=False)
    op.create_index('idx_account_customer_status', 'accounts', ['customer_id', 'account_status'], unique=False)
    op.create_index(op.f('ix_accounts_account_name'), 'accounts', ['account_name'], unique=False)
    op.create_index(op.f('ix_accounts_account_status'), 'accounts', ['account_status'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_external_account_id'), 'accounts', ['external_account_id'], unique=False)
    op.create_index(op.f('ix_accounts_industry'), 'accounts', ['industry'], unique=False)
    op.create_index(op.f('ix_accounts_region'), 'accounts', ['region'], unique=False)
    op.create_table('csv_upload_staging',
    sa.Column('staging_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('csv_content', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('staging_id'),
    sa.UniqueConstraint('customer_id', 'file_type', name='unique_customer_staged_file')
    )
    op.create_index(op.f('ix_csv_upload_staging_customer_id'), 'csv_upload_staging', ['customer_id'], unique=False)
    op.create_table('csv_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('key_kind', sa.String(length=10), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('process_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_uploads_customer_id'), 'csv_uploads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_csv_uploads_sha256'), 'csv_uploads', ['sha256'], unique=False)
    op.create_index(op.f('ix_csv_uploads_uploaded_at'), 'csv_uploads', ['uploaded_at'], unique=False)
    op.create_table('customer_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('allowed_account_ids', sa.JSON(), nullable=True),
    sa.Column('partner_tier', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_api_keys_key_prefix'), 'customer_api_keys', ['key_prefix'], unique=False)
    op.create_table('customer_configs',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('kpi_upload_mode', sa.String(), nullable=True),
    sa.Column('column_map', sa.JSON(), nullable=True),
    sa.Column('category_weights', sa.Text(), nullable=True),
    sa.Column('master_file_name', sa.String(), nullable=True),
    sa.Column('openai_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('openai_api_key_updated_at', sa.DateTime(), nullable=True),
    sa.Column('vertical', sa.String(length=50), nullable=True),
    sa.Column('pillar_weights', sa.JSON(), nullable=True),
    sa.Column('enabled_kpis', sa.JSON(), nullable=True),
    sa.Column('kpi_overrides', sa.JSON(), nullable=True),
    sa.Column('kpi_weights', sa.JSON(), nullable=True),
    sa.Column('kpi_definitions', sa.JSON(), nullable=True),
    sa.Column('lifecycle_stage_weights', sa.JSON(), nullable=True),
    sa.Column('nomenclature_overrides', sa.JSON(), nullable=True),
    sa.Column('config_version', sa.String(length=20), nullable=True),
    sa.Column('customized_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('feature_toggles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'feature_name', name='unique_customer_feature')
    )
    op.create_index(op.f('ix_feature_toggles_customer_id'), 'feature_toggles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_feature_toggles_feature_name'), 'feature_toggles', ['feature_name'], unique=False)
    op.create_table('llm_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_estimate_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_log_created_at'), 'llm_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_log_customer_id'), 'llm_usage_log', ['customer_id'], unique=False)
    op.create_table('process_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vertical', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('timings', sa.JSON(), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('upload_ids', sa.JSON(), nullable=True),
    sa.Column('key_kind', sa.String(length=10), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('generator_version', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_runs_customer_id'), 'process_runs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_process_runs_run_id'), 'process_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_process_runs_started_at'), 'process_runs', ['started_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=60), nullable=True),
    sa.Column('customer_uuid', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('vertical', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('allowed_account_ids', sa.JSON(), nullable=True),
    sa.Column('allowed_customer_ids', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_contractor', sa.Boolean(), nullable=True),
    sa.Column('magic_link_token', sa.String(length=100), nullable=True),
    sa.Column('magic_link_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('customer_id', 'user_name', name='unique_customer_username'),
    sa.UniqueConstraint('email', name='unique_user_email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_magic_link_token'), 'users', ['magic_link_token'], unique=False)
    op.create_table('wizard_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('wizard', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wizard_runs_created_at'), 'wizard_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_wizard_runs_customer_id'), 'wizard_runs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_wizard_runs_run_id'), 'wizard_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_wizard_runs_status'), 'wizard_runs', ['status'], unique=False)
    op.create_index(op.f('ix_wizard_runs_wizard'), 'wizard_runs', ['wizard'], unique=False)
    op.create_table('context_nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('node_subtype', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('revenue_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revenue_impact_type', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('source_event_id', sa.String(length=200), nullable=True),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('weight_decay', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index('idx_ctx_node_account_type', 'context_nodes', ['account_id', 'node_type'], unique=False)
    op.create_index('idx_ctx_node_customer', 'context_nodes', ['customer_id', 'node_type'], unique=False)
    op.create_index('idx_ctx_node_occurred', 'context_nodes', ['account_id', 'occurred_at'], unique=False)
    op.create_index('idx_ctx_node_source', 'context_nodes', ['source_platform', 'source_event_id'], unique=False)
    op.create_index('idx_ctx_node_tier_expires', 'context_nodes', ['tier', 'expires_at'], unique=False)
    op.create_index(op.f('ix_context_nodes_account_id'), 'context_nodes', ['account_id'], unique=False)
    op.create_index(op.f('ix_context_nodes_customer_id'), 'context_nodes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_context_nodes_node_subtype'), 'context_nodes', ['node_subtype'], unique=False)
    op.create_index(op.f('ix_context_nodes_node_type'), 'context_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_context_nodes_occurred_at'), 'context_nodes', ['occurred_at'], unique=False)
    op.create_table('health_scores',
    sa.Column('health_score_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('measurement_month', sa.Date(), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('change_from_last_month', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kpi_only_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('qual_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('divergence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('early_warning', sa.String(length=24), nullable=True),
    sa.Column('contributing_pillars', sa.JSON(), nullable=True),
    sa.Column('pillar_weights', sa.JSON(), nullable=True),
    sa.Column('kpi_weights', sa.JSON(), nullable=True),
    sa.Column('kpi_codes_used', sa.JSON(), nullable=True),
    sa.Column('kpi_codes_dropped', sa.JSON(), nullable=True),
    sa.Column('weight_source', sa.String(length=24), nullable=True),
    sa.Column('catalog_version', sa.String(length=20), nullable=True),
    sa.Column('taxonomy_version', sa.String(length=20), nullable=True),
    sa.Column('scorer_version', sa.String(length=20), nullable=True),
    sa.Column('input_upload_id', sa.Integer(), nullable=True),
    sa.Column('process_run_id', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('health_score_id'),
    sa.UniqueConstraint('account_id', 'measurement_month', name='unique_health_score')
    )
    op.create_index('idx_health_score_account_month', 'health_scores', ['account_id', 'measurement_month'], unique=False)
    op.create_index('idx_health_score_status', 'health_scores', ['health_status'], unique=False)
    op.create_index(op.f('ix_health_scores_account_id'), 'health_scores', ['account_id'], unique=False)
    op.create_index(op.f('ix_health_scores_measurement_month'), 'health_scores', ['measurement_month'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.String(length=80), nullable=False),
    sa.Column('playbook_version', sa.String(length=20), nullable=False),
    sa.Column('action_class', sa.String(length=20), nullable=False),
    sa.Column('approval_mode', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=True),
    sa.Column('trigger_key', sa.String(length=64), nullable=False),
    sa.Column('trigger_episode_ids', sa.JSON(), nullable=False),
    sa.Column('trigger_node_ids', sa.JSON(), nullable=False),
    sa.Column('trigger_roles', sa.JSON(), nullable=False),
    sa.Column('trigger_quote', sa.Text(), nullable=True),
    sa.Column('evaluated_as_of', sa.DateTime(), nullable=True),
    sa.Column('expected_outcome_types', sa.JSON(), nullable=False),
    sa.Column('expected_window_days', sa.Integer(), nullable=False),
    sa.Column('exposure_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('proposed_at', sa.DateTime(), nullable=False),
    sa.Column('proposed_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_by_key_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_report_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_state', sa.String(length=12), nullable=True),
    sa.Column('closed_by', sa.String(length=120), nullable=True),
    sa.Column('outcome_node_id', sa.Integer(), nullable=True),
    sa.Column('outcome_in_window', sa.Boolean(), nullable=True),
    sa.Column('outcome_expected', sa.Boolean(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'playbook_id', 'trigger_key', name='uq_intervention_trigger')
    )
    op.create_index('idx_intervention_customer_state', 'interventions', ['customer_id', 'state'], unique=False)
    op.create_index(op.f('ix_interventions_account_id'), 'interventions', ['account_id'], unique=False)
    op.create_index(op.f('ix_interventions_customer_id'), 'interventions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_interventions_playbook_id'), 'interventions', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_interventions_proposed_at'), 'interventions', ['proposed_at'], unique=False)
    op.create_index(op.f('ix_interventions_state'), 'interventions', ['state'], unique=False)
    op.create_table('journey_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('journey_json', sa.JSON(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=True),
    sa.Column('journey_pattern', sa.String(length=50), nullable=True),
    sa.Column('generator_version', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'account_id', name='unique_account_journey')
    )
    op.create_index(op.f('ix_journey_data_account_id'), 'journey_data', ['account_id'], unique=False)
    op.create_index(op.f('ix_journey_data_customer_id'), 'journey_data', ['customer_id'], unique=False)
    op.create_table('kpi_measurements',
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kpi_code', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pillar', sa.String(length=10), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('kpi_id'),
    sa.UniqueConstraint('account_id', 'kpi_code', 'measured_at', name='unique_kpi_measurement')
    )
    op.create_index('idx_kpi_measurement_account_code', 'kpi_measurements', ['account_id', 'kpi_code'], unique=False)
    op.create_index(op.f('ix_kpi_measurements_account_id'), 'kpi_measurements', ['account_id'], unique=False)
    op.create_index(op.f('ix_kpi_measurements_kpi_code'), 'kpi_measurements', ['kpi_code'], unique=False)
    op.create_index(op.f('ix_kpi_measurements_measured_at'), 'kpi_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_kpi_measurements_pillar'), 'kpi_measurements', ['pillar'], unique=False)
    op.create_index(op.f('ix_kpi_measurements_upload_id'), 'kpi_measurements', ['upload_id'], unique=False)
    op.create_table('qualitative_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('stakeholder_level', sa.String(length=50), nullable=True),
    sa.Column('stakeholder_title', sa.String(length=255), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('is_narrative_signal', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('relationship_sentiment', sa.Float(), nullable=True),
    sa.Column('product_sentiment', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('escalation_probability', sa.Float(), nullable=True),
    sa.Column('intent_signals', sa.JSON(), nullable=True),
    sa.Column('stakeholder_roles', sa.JSON(), nullable=True),
    sa.Column('suggested_action', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.Column('llm_model_version', sa.String(length=100), nullable=True),
    sa.Column('composite_signal_id', sa.String(length=100), nullable=True),
    sa.Column('dedup_confidence', sa.Float(), nullable=True),
    sa.Column('cg_node_id', sa.Integer(), nullable=True),
    sa.Column('alert_suppressed', sa.Boolean(), nullable=True),
    sa.Column('structural_urgency', sa.String(length=20), nullable=True),
    sa.Column('effective_urgency', sa.String(length=20), nullable=True),
    sa.Column('consent_verified', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('extractions', sa.JSON(), nullable=True),
    sa.Column('use_case', sa.String(length=120), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'signal_id', name='uq_customer_signal_id')
    )
    op.create_index('idx_signals_customer_account', 'qualitative_signals', ['customer_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_qualitative_signals_account_id'), 'qualitative_signals', ['account_id'], unique=False)
    op.create_index(op.f('ix_qualitative_signals_content_hash'), 'qualitative_signals', ['content_hash'], unique=False)
    op.create_index(op.f('ix_qualitative_signals_customer_id'), 'qualitative_signals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_qualitative_signals_sentiment'), 'qualitative_signals', ['sentiment'], unique=False)
    op.create_index(op.f('ix_qualitative_signals_signal_date'), 'qualitative_signals', ['signal_date'], unique=False)
    op.create_index(op.f('ix_qualitative_signals_signal_type'), 'qualitative_signals', ['signal_type'], unique=False)
    op.create_table('signal_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(length=100), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('from_subtype', sa.String(length=100), nullable=True),
    sa.Column('to_subtype', sa.String(length=100), nullable=True),
    sa.Column('was_flagged', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_reviews_account_id'), 'signal_reviews', ['account_id'], unique=False)
    op.create_index(op.f('ix_signal_reviews_created_at'), 'signal_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_signal_reviews_customer_id'), 'signal_reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_signal_reviews_signal_id'), 'signal_reviews', ['signal_id'], unique=False)
    op.create_table('context_edges',
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(length=30), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('revenue_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revenue_impact_type', sa.String(length=30), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['from_node_id'], ['context_nodes.node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['context_nodes.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index('idx_ctx_edge_from', 'context_edges', ['from_node_id', 'edge_type'], unique=False)
    op.create_index('idx_ctx_edge_pair', 'context_edges', ['from_node_id', 'to_node_id', 'edge_type'], unique=False)
    op.create_index('idx_ctx_edge_superseded_by', 'context_edges', ['superseded_by'], unique=False)
    op.create_index('idx_ctx_edge_to', 'context_edges', ['to_node_id', 'edge_type'], unique=False)
    op.create_index('idx_ctx_edge_type', 'context_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_context_edges_customer_id'), 'context_edges', ['customer_id'], unique=False)
    op.create_index(op.f('ix_context_edges_edge_type'), 'context_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_context_edges_from_node_id'), 'context_edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_context_edges_to_node_id'), 'context_edges', ['to_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_edges_to_node_id'), table_name='context_edges')
    op.drop_index(op.f('ix_context_edges_from_node_id'), table_name='context_edges')
    op.drop_index(op.f('ix_context_edges_edge_type'), table_name='context_edges')
    op.drop_index(op.f('ix_context_edges_customer_id'), table_name='context_edges')
    op.drop_index('idx_ctx_edge_type', table_name='context_edges')
    op.drop_index('idx_ctx_edge_to', table_name='context_edges')
    op.drop_index('idx_ctx_edge_superseded_by', table_name='context_edges')
    op.drop_index('idx_ctx_edge_pair', table_name='context_edges')
    op.drop_index('idx_ctx_edge_from', table_name='context_edges')
    op.drop_table('context_edges')
    op.drop_index(op.f('ix_signal_reviews_signal_id'), table_name='signal_reviews')
    op.drop_index(op.f('ix_signal_reviews_customer_id'), table_name='signal_reviews')
    op.drop_index(op.f('ix_signal_reviews_created_at'), table_name='signal_reviews')
    op.drop_index(op.f('ix_signal_reviews_account_id'), table_name='signal_reviews')
    op.drop_table('signal_reviews')
    op.drop_index(op.f('ix_qualitative_signals_signal_type'), table_name='qualitative_signals')
    op.drop_index(op.f('ix_qualitative_signals_signal_date'), table_name='qualitative_signals')
    op.drop_index(op.f('ix_qualitative_signals_sentiment'), table_name='qualitative_signals')
    op.drop_index(op.f('ix_qualitative_signals_customer_id'), table_name='qualitative_signals')
    op.drop_index(op.f('ix_qualitative_signals_content_hash'), table_name='qualitative_signals')
    op.drop_index(op.f('ix_qualitative_signals_account_id'), table_name='qualitative_signals')
    op.drop_index('idx_signals_customer_account', table_name='qualitative_signals')
    op.drop_table('qualitative_signals')
    op.drop_index(op.f('ix_kpi_measurements_upload_id'), table_name='kpi_measurements')
    op.drop_index(op.f('ix_kpi_measurements_pillar'), table_name='kpi_measurements')
    op.drop_index(op.f('ix_kpi_measurements_measured_at'), table_name='kpi_measurements')
    op.drop_index(op.f('ix_kpi_measurements_kpi_code'), table_name='kpi_measurements')
    op.drop_index(op.f('ix_kpi_measurements_account_id'), table_name='kpi_measurements')
    op.drop_index('idx_kpi_measurement_account_code', table_name='kpi_measurements')
    op.drop_table('kpi_measurements')
    op.drop_index(op.f('ix_journey_data_customer_id'), table_name='journey_data')
    op.drop_index(op.f('ix_journey_data_account_id'), table_name='journey_data')
    op.drop_table('journey_data')
    op.drop_index(op.f('ix_interventions_state'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_proposed_at'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_playbook_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_customer_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_account_id'), table_name='interventions')
    op.drop_index('idx_intervention_customer_state', table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_health_scores_measurement_month'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_account_id'), table_name='health_scores')
    op.drop_index('idx_health_score_status', table_name='health_scores')
    op.drop_index('idx_health_score_account_month', table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_context_nodes_occurred_at'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_node_type'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_node_subtype'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_customer_id'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_account_id'), table_name='context_nodes')
    op.drop_index('idx_ctx_node_tier_expires', table_name='context_nodes')
    op.drop_index('idx_ctx_node_source', table_name='context_nodes')
    op.drop_index('idx_ctx_node_occurred', table_name='context_nodes')
    op.drop_index('idx_ctx_node_customer', table_name='context_nodes')
    op.drop_index('idx_ctx_node_account_type', table_name='context_nodes')
    op.drop_table('context_nodes')
    op.drop_index(op.f('ix_wizard_runs_wizard'), table_name='wizard_runs')
    op.drop_index(op.f('ix_wizard_runs_status'), table_name='wizard_runs')
    op.drop_index(op.f('ix_wizard_runs_run_id'), table_name='wizard_runs')
    op.drop_index(op.f('ix_wizard_runs_customer_id'), table_name='wizard_runs')
    op.drop_index(op.f('ix_wizard_runs_created_at'), table_name='wizard_runs')
    op.drop_table('wizard_runs')
    op.drop_index(op.f('ix_users_magic_link_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_process_runs_started_at'), table_name='process_runs')
    op.drop_index(op.f('ix_process_runs_run_id'), table_name='process_runs')
    op.drop_index(op.f('ix_process_runs_customer_id'), table_name='process_runs')
    op.drop_table('process_runs')
    op.drop_index(op.f('ix_llm_usage_log_customer_id'), table_name='llm_usage_log')
    op.drop_index(op.f('ix_llm_usage_log_created_at'), table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    op.drop_index(op.f('ix_feature_toggles_feature_name'), table_name='feature_toggles')
    op.drop_index(op.f('ix_feature_toggles_customer_id'), table_name='feature_toggles')
    op.drop_table('feature_toggles')
    op.drop_table('customer_configs')
    op.drop_index(op.f('ix_customer_api_keys_key_prefix'), table_name='customer_api_keys')
    op.drop_table('customer_api_keys')
    op.drop_index(op.f('ix_csv_uploads_uploaded_at'), table_name='csv_uploads')
    op.drop_index(op.f('ix_csv_uploads_sha256'), table_name='csv_uploads')
    op.drop_index(op.f('ix_csv_uploads_customer_id'), table_name='csv_uploads')
    op.drop_table('csv_uploads')
    op.drop_index(op.f('ix_csv_upload_staging_customer_id'), table_name='csv_upload_staging')
    op.drop_table('csv_upload_staging')
    op.drop_index(op.f('ix_accounts_region'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_industry'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_external_account_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_name'), table_name='accounts')
    op.drop_index('idx_account_customer_status', table_name='accounts')
    op.drop_index('idx_account_customer_region', table_name='accounts')
    op.drop_index('idx_account_customer_industry', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_tool_audit_log_tool'), table_name='tool_audit_log')
    op.drop_index(op.f('ix_tool_audit_log_outcome'), table_name='tool_audit_log')
    op.drop_index(op.f('ix_tool_audit_log_customer_id'), table_name='tool_audit_log')
    op.drop_index(op.f('ix_tool_audit_log_at'), table_name='tool_audit_log')
    op.drop_table('tool_audit_log')
    op.drop_table('customers')
    # ### end Alembic commands ###
